language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

php:
  - 7.1
  - 7.2

matrix:
  fast_finish: true

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-dist

script:
  - php vendor/bin/php-cs-fixer fix -v --diff --dry-run
  - php vendor/bin/phpunit --coverage-text --coverage-clover build/coverage/xml tests

after_success:
  - php vendor/bin/codacycoverage clover build/coverage/xml

notifications:
  email: false

