# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/7.1.18-cli-node-browsers

    working_directory: ~/hello-world

    steps:
      - checkout
      - run: sudo composer self-update

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          - v1-dependencies-

      - run: composer install --no-interaction --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run: ./vendor/bin/php-cs-fixer fix -v --diff --dry-run
      - run: ./vendor/bin/phpunit --coverage-text --coverage-clover build/coverage/xml tests
